### ISSUE TITLE
Patched ROM not created in pwd due to Unicode chars in the path

### ISSUE THREAD

**Issue by pokeholmes001** [nozwock/yanu#1]
When updating the pokemon shield rom at the end of the update process the rom does not appear and check that it is not in any other folder, the rom file is not created 

https://user-images.githubusercontent.com/97064511/222853266-f82eaba3-2054-4111-9a35-b1bdc489cbe8.mp4

https://user-images.githubusercontent.com/97064511/222853702-3b9996b3-979d-4b9c-b39d-0c40252c15ed.mp4

https://user-images.githubusercontent.com/97064511/222853713-2905b257-9d18-4205-bcab-e7212c508a3a.mp4

**Comment by pokeholmes001** [comment]
Sorry if I misspelled something as I am using Google translate to write this in your language which I think is English. but I ask you please to solve this error that it does not create the updated rom file

**Comment by nozwock** [comment]
@pokeholmes001 Send logs, they're in the same directory as `yanu`

**Comment by nozwock** [comment]
I think the issue is because of Japanese character in the folder name, try removing that and see if it works.

**Comment by nozwock** [comment]
@pokeholmes001 This bug is caused due to `hactool`/`hacPack`, they can't handle UTF-8 characters but only ASCII.
I'll fix this in a future version with a workaround :+1:

**Comment by pokeholmes001** [comment]
@nozwock ok, and thank you very much for creating this ROM updater

**Comment by nozwock** [comment]
@pokeholmes001 This is hopefully fixed in [v0.2.2](https://github.com/nozwock/yanu/releases/tag/0.2.2)

**Comment by pokeholmes001** [comment]
@nozwock You already solved it 😃 I don't know what you did but you managed to solve it, you are great and thank you for your work, this nsp updater is much easier to use than the other nsp updater really thank you very much
![IMG_20230304_090745](https://user-images.githubusercontent.com/97064511/222900391-286f2b81-5f33-4bd1-abf9-f8aed8d19b06.jpg)
