### ISSUE TITLE
Error occured while merging Diablo 3 with language pack

### ISSUE THREAD

**Issue by dzikk** [nozwock/yanu#10]
Hi
as in title I got error while merging Diablo 3 with language pack.

Failed to extract (location to game base).

<details><summary>Logs</summary>

```
Location:
   [35mC:\Users\user\Desktop\yanu\src\hac\rom.rs[0m:[35m83[0m
[2m2023-03-26T11:33:53.962639Z[0m [32m INFO[0m [2myanu[0m[2m:[0m Launching yanu on windows!
[2m2023-03-26T11:33:53.962680Z[0m [32m INFO[0m [2myanu[0m[2m:[0m [3mversion[0m[2m=[0m"0.6.1"
[2m2023-03-26T11:33:58.820721Z[0m [32m INFO[0m [2myanu::utils[0m[2m:[0m Selected file [3mpath[0m[2m=[0m"C:\\Users\\Tomek\\Downloads\\Diablo 3 Eternal Collection [ UPDATE 2.7.4.84040 ] [01001B300B9BE000].nsp"
[2m2023-03-26T11:34:04.566483Z[0m [32m INFO[0m [2myanu::utils[0m[2m:[0m Selected file [3mpath[0m[2m=[0m"C:\\Users\\Tomek\\Downloads\\Compressed\\D3-EC-NSwTcH-LANG-[POLISHPACK]-NSP-Ziperto\\Diablo III Eternal Collection [Polish Language Pack] [01001B300B9BF00E][v0].nsp"
[2m2023-03-26T11:34:05.519045Z[0m [32m INFO[0m [2myanu[0m[2m:[0m Started patching!
[2m2023-03-26T11:34:05.533731Z[0m [32m INFO[0m [2myanu::hac::rom[0m[2m:[0m Extracting [3mself.path[0m[2m=[0m"C:\\Users\\Tomek\\Downloads\\Diablo 3 Eternal Collection [ UPDATE 2.7.4.84040 ] [01001B300B9BE000].nsp"
[2m2023-03-26T11:34:05.594488Z[0m [31mERROR[0m [2myanu::hac::rom[0m[2m:[0m Encountered an error while unpacking NSP [3mstderr[0m[2m=[0m
ERROR: ResultFsUsableSpaceNotEnough (2002-0030)

Additional information:
   at LibHac.Common.ThrowHelper.ThrowResult(Result) + 0x2c
   at LibHac.Tools.FsSystem.FileSystemExtensions.Extract(IFileSystem, String, IProgressReport) + 0x63
   at hactoolnet.ProcessPfs.Process(Context) + 0x1af
   at hactoolnet.Program.Run(String[]) + 0x2ca
   at hactoolnet.Program.Main(String[]) + 0x27

[2m2023-03-26T11:34:05.595163Z[0m [31mERROR[0m [2myanu[0m[2m:[0m [3merr[0m[2m=[0m
   0: [91mFailed to extract "C:\\Users\\Tomek\\Downloads\\Diablo 3 Eternal Collection [ UPDATE 2.7.4.84040 ] [01001B300B9BE000].nsp"[0m

Location:
   [35mC:\Users\user\Desktop\yanu\src\hac\rom.rs[0m:[35m83[0m
```

</details>

**Comment by nekomekoraiyuu** [comment]
Hmm but do you have enough space to extract the rom?

**Comment by nozwock** [comment]
> Hmm but do you have enough space to extract the rom?

Looks like it. Also this `"D3-EC-NSwTcH-LANG-[POLISHPACK]-NSP-Ziperto\Diablo III Eternal Collection [Polish Language Pack] [01001B300B9BF00E][v0].nsp"` looks like a custom update? Not sure if it'd would work besides the space issue.

**Comment by dzikk** [comment]
![yanu](https://user-images.githubusercontent.com/22121054/227791322-00a1038f-1b5e-487c-98dc-a8e44aeea2ea.JPG)
about free space - yes it was the problem :) but now I have something else
what does it mean?

**Comment by nozwock** [comment]
> ![yanu](https://user-images.githubusercontent.com/22121054/227791322-00a1038f-1b5e-487c-98dc-a8e44aeea2ea.JPG)
> about free space - yes it was the problem :) but now I have something else
> what does it mean?

Probably because it's a custom update NSP and doesn't seem to include a program NCA.

What's the size of this update NSP? Probably small ig.

**Comment by dzikk** [comment]
its language pack = 5,27GB

**Comment by nozwock** [comment]
Well send logs or I can't help.

**Comment by dzikk** [comment]
Sorry last time logs was ignored when I attached them.

`[2m2023-03-26T17:12:59.200973Z[0m [32m INFO[0m [2myanu[0m[2m:[0m Launching yanu on windows!
[2m2023-03-26T17:12:59.201014Z[0m [32m INFO[0m [2myanu[0m[2m:[0m [3mversion[0m[2m=[0m"0.6.1"
[2m2023-03-26T17:13:05.672718Z[0m [32m INFO[0m [2myanu::utils[0m[2m:[0m Selected file [3mpath[0m[2m=[0m"C:\\Users\\Tomek\\Downloads\\Diablo_III_Eternal_Collection__switch-xci.com__v0_.nsp"
[2m2023-03-26T17:13:10.156618Z[0m [32m INFO[0m [2myanu::utils[0m[2m:[0m Selected file [3mpath[0m[2m=[0m"M:\\d3\\polish.nsp"
[2m2023-03-26T17:13:11.416764Z[0m [32m INFO[0m [2myanu[0m[2m:[0m Started patching!
[2m2023-03-26T17:13:11.424090Z[0m [32m INFO[0m [2myanu::hac::rom[0m[2m:[0m Extracting [3mself.path[0m[2m=[0m"C:\\Users\\Tomek\\Downloads\\Diablo_III_Eternal_Collection__switch-xci.com__v0_.nsp"
[2m2023-03-26T17:13:42.538782Z[0m [32m INFO[0m [2myanu::hac::rom[0m[2m:[0m Extraction done [3mself.path[0m[2m=[0m"C:\\Users\\Tomek\\Downloads\\Diablo_III_Eternal_Collection__switch-xci.com__v0_.nsp" [3mto[0m[2m=[0m"C:\\Users\\Tomek\\Downloads\\Programs\\.tmp7eSdoN"
[2m2023-03-26T17:13:42.546125Z[0m [32m INFO[0m [2myanu::hac::rom[0m[2m:[0m Extracting [3mself.path[0m[2m=[0m"M:\\d3\\polish.nsp"
[2m2023-03-26T17:14:11.490033Z[0m [32m INFO[0m [2myanu::hac::rom[0m[2m:[0m Extraction done [3mself.path[0m[2m=[0m"M:\\d3\\polish.nsp" [3mto[0m[2m=[0m"C:\\Users\\Tomek\\Downloads\\Programs\\.tmp9oXtl4"
[2m2023-03-26T17:14:11.491676Z[0m [32m INFO[0m [2myanu::hac::rom[0m[2m:[0m Deriving TitleKey [3mnsp[0m[2m=[0m"C:\\Users\\Tomek\\Downloads\\Diablo_III_Eternal_Collection__switch-xci.com__v0_.nsp"
[2m2023-03-26T17:14:11.491968Z[0m [32m INFO[0m [2myanu::hac::ticket[0m[2m:[0m Reading ticket [3mtik[0m[2m=[0m"C:\\Users\\Tomek\\Downloads\\Programs\\.tmp7eSdoN\\01001b300b9be0000000000000000005.tik"
[2m2023-03-26T17:14:11.492183Z[0m [34mDEBUG[0m [2myanu::hac::ticket[0m[2m:[0m [3mtitle_key[0m[2m=[0m"01001b300b9be0000000000000000005=72f594dbfb8a35063448ed0459339391"
[2m2023-03-26T17:14:11.492232Z[0m [32m INFO[0m [2myanu::hac::rom[0m[2m:[0m Derived TitleKey successfully!
[2m2023-03-26T17:14:11.492235Z[0m [32m INFO[0m [2myanu::hac::rom[0m[2m:[0m Deriving TitleKey [3mnsp[0m[2m=[0m"M:\\d3\\polish.nsp"
[2m2023-03-26T17:14:11.492462Z[0m [32m INFO[0m [2myanu::hac::ticket[0m[2m:[0m Reading ticket [3mtik[0m[2m=[0m"C:\\Users\\Tomek\\Downloads\\Programs\\.tmp9oXtl4\\01001b300b9bf00e0000000000000005.tik"
[2m2023-03-26T17:14:11.492498Z[0m [34mDEBUG[0m [2myanu::hac::ticket[0m[2m:[0m [3mtitle_key[0m[2m=[0m"01001b300b9bf00e0000000000000005=634b231c039968ee2b4b5b2a35914bb8"
[2m2023-03-26T17:14:11.492533Z[0m [32m INFO[0m [2myanu::hac::rom[0m[2m:[0m Derived TitleKey successfully!
[2m2023-03-26T17:14:11.492536Z[0m [32m INFO[0m [2myanu::hac::patch[0m[2m:[0m Storing TitleKeys [3mkeyfile[0m[2m=[0m"C:\\Users\\Tomek\\.switch\\title.keys"
[2m2023-03-26T17:14:11.493362Z[0m [32m INFO[0m [2myanu::hac::rom[0m[2m:[0m Identifying TitleID and ContentType [3mnca[0m[2m=[0m"C:\\Users\\Tomek\\Downloads\\Programs\\.tmp7eSdoN\\244b84153edddf42407aa2a03572202a.nca"
[2m2023-03-26T17:14:11.540899Z[0m [34mDEBUG[0m [2myanu::hac::rom[0m[2m:[0m [3mtitle_id[0m[2m=[0mSome("01001B300B9BE000")
[2m2023-03-26T17:14:11.541198Z[0m [34mDEBUG[0m [2myanu::hac::rom[0m[2m:[0m [3mcontent_type[0m[2m=[0mSome(Program)
[2m2023-03-26T17:14:11.541284Z[0m [32m INFO[0m [2myanu::hac::rom[0m[2m:[0m Identifying TitleID and ContentType [3mnca[0m[2m=[0m"C:\\Users\\Tomek\\Downloads\\Programs\\.tmp7eSdoN\\e0197ee7f5aa5837643e8d982d4e3344.nca"
[2m2023-03-26T17:14:11.577981Z[0m [34mDEBUG[0m [2myanu::hac::rom[0m[2m:[0m [3mtitle_id[0m[2m=[0mSome("01001B300B9BE000")
[2m2023-03-26T17:14:11.577994Z[0m [34mDEBUG[0m [2myanu::hac::rom[0m[2m:[0m [3mcontent_type[0m[2m=[0mSome(Control)
[2m2023-03-26T17:14:11.578085Z[0m [32m INFO[0m [2myanu::hac::rom[0m[2m:[0m Identifying TitleID and ContentType [3mnca[0m[2m=[0m"C:\\Users\\Tomek\\Downloads\\Programs\\.tmp7eSdoN\\ade5aee315b23e0d209fc8b3bb7965eb.nca"
[2m2023-03-26T17:14:11.608449Z[0m [34mDEBUG[0m [2myanu::hac::rom[0m[2m:[0m [3mtitle_id[0m[2m=[0mSome("01001B300B9BE000")
[2m2023-03-26T17:14:11.608462Z[0m [34mDEBUG[0m [2myanu::hac::rom[0m[2m:[0m [3mcontent_type[0m[2m=[0mSome(Manual)
[2m2023-03-26T17:14:11.608557Z[0m [32m INFO[0m [2myanu::hac::rom[0m[2m:[0m Identifying TitleID and ContentType [3mnca[0m[2m=[0m"C:\\Users\\Tomek\\Downloads\\Programs\\.tmp7eSdoN\\93a483f1d8853d85ac98071070f5a547.nca"
[2m2023-03-26T17:14:11.639216Z[0m [34mDEBUG[0m [2myanu::hac::rom[0m[2m:[0m [3mtitle_id[0m[2m=[0mSome("01001B300B9BE000")
[2m2023-03-26T17:14:11.639230Z[0m [34mDEBUG[0m [2myanu::hac::rom[0m[2m:[0m [3mcontent_type[0m[2m=[0mSome(Manual)
[2m2023-03-26T17:14:11.639361Z[0m [32m INFO[0m [2myanu::hac::rom[0m[2m:[0m Identifying TitleID and ContentType [3mnca[0m[2m=[0m"C:\\Users\\Tomek\\Downloads\\Programs\\.tmp7eSdoN\\87812cfdcc986b599d340eda9746d428.cnmt.nca"
[2m2023-03-26T17:14:11.670762Z[0m [34mDEBUG[0m [2myanu::hac::rom[0m[2m:[0m [3mtitle_id[0m[2m=[0mSome("01001B300B9BE000")
[2m2023-03-26T17:14:11.670788Z[0m [34mDEBUG[0m [2myanu::hac::rom[0m[2m:[0m [3mcontent_type[0m[2m=[0mSome(Meta)
[2m2023-03-26T17:14:11.670813Z[0m [34mDEBUG[0m [2myanu::hac::patch[0m[2m:[0m [3mbase_nca[0m[2m=[0mNca { path: "C:\\Users\\Tomek\\Downloads\\Programs\\.tmp7eSdoN\\244b84153edddf42407aa2a03572202a.nca", title_id: Some("01001B300B9BE000"), content_type: Program }
[2m2023-03-26T17:14:11.675720Z[0m [32m INFO[0m [2myanu::hac::rom[0m[2m:[0m Identifying TitleID and ContentType [3mnca[0m[2m=[0m"C:\\Users\\Tomek\\Downloads\\Programs\\.tmp9oXtl4\\90b7a072ba5e83270fc48bc9c0267ad0.nca"
[2m2023-03-26T17:14:11.796738Z[0m [34mDEBUG[0m [2myanu::hac::rom[0m[2m:[0m [3mtitle_id[0m[2m=[0mSome("01001B300B9BF00E")
[2m2023-03-26T17:14:11.797989Z[0m [32m INFO[0m [2myanu::hac::rom[0m[2m:[0m Identifying TitleID and ContentType [3mnca[0m[2m=[0m"C:\\Users\\Tomek\\Downloads\\Programs\\.tmp9oXtl4\\28c688b9d65b9456f6bde3b5b2518c74.cnmt.nca"
[2m2023-03-26T17:14:11.830526Z[0m [34mDEBUG[0m [2myanu::hac::rom[0m[2m:[0m [3mtitle_id[0m[2m=[0mSome("01001B300B9BF00E")
[2m2023-03-26T17:14:11.830552Z[0m [34mDEBUG[0m [2myanu::hac::rom[0m[2m:[0m [3mcontent_type[0m[2m=[0mSome(Meta)
[2m2023-03-26T17:14:11.830560Z[0m [33m WARN[0m [2myanu::hac::patch[0m[2m:[0m [3merr[0m[2m=[0m
   0: [91mMatching variant not found[0m

Location:
   [35mC:\Users\user\Desktop\yanu\src\hac\rom.rs[0m:[35m229[0m
[2m2023-03-26T17:14:11.834641Z[0m [32m INFO[0m [2myanu::hac::patch[0m[2m:[0m Using fallback extractor Hac2l
[2m2023-03-26T17:14:11.834732Z[0m [32m INFO[0m [2myanu::hac::rom[0m[2m:[0m Identifying TitleID and ContentType [3mnca[0m[2m=[0m"C:\\Users\\Tomek\\Downloads\\Programs\\.tmp9oXtl4\\90b7a072ba5e83270fc48bc9c0267ad0.nca"
[2m2023-03-26T17:14:11.863239Z[0m [34mDEBUG[0m [2myanu::hac::rom[0m[2m:[0m [3mtitle_id[0m[2m=[0mSome("01001B300B9BF00E")
[2m2023-03-26T17:14:11.863298Z[0m [33m WARN[0m [2myanu::hac::patch[0m[2m:[0m [3merr[0m[2m=[0m
   0: [91mMatching variant not found[0m

Location:
   [35mC:\Users\user\Desktop\yanu\src\hac\rom.rs[0m:[35m229[0m
[2m2023-03-26T17:14:12.729249Z[0m [31mERROR[0m [2myanu[0m[2m:[0m [3merr[0m[2m=[0m
   0: [91mCouldn't find a Update NCA (Program Type) in "M:\\d3\\polish.nsp"[0m

Location:
   [35mC:\Users\user\Desktop\yanu\src\hac\patch.rs[0m:[35m458[0m
`

**Comment by dzikk** [comment]
any news?

**Comment by nozwock** [comment]
I'm busy, anyways looking at the logs I can't really help, not enough.
I don't have this particular NSP myself so can't check.

Ig you'll have to wait till I improve the logs to include more information, that way maybe we'll have enough data to know why it isn't working.

**Comment by nozwock** [comment]
I'm busy, anyways looking at the logs I can't really help, not enough.
I don't have this particular NSP myself so can't check.

Ig you'll have to wait till I improve the logs to include more information, that way maybe we'll have enough data to know why it isn't working.

What even is `polish.nsp` anyways?
Mod? You aren't supposed to install mods this way.

**Comment by dzikk** [comment]
Its polish language pack (polish speech). Without this pack, game is with english speech.

**Comment by nozwock** [comment]
it doesn't work because it's not an update, it's a patch/mod.

**Comment by vannessqn** [comment]
@nozwock just a quick question do I need to update yanu on android? If yes how do I do that

**Comment by dzikk** [comment]
> 

I tried one time but it was to complicated for me. I hoped that with your app I will manage it simply and quickly ;)

**Comment by nozwock** [comment]
Just run the installation command again.

**Comment by nozwock** [comment]
Also I'm closing this issue for now.
I don't think the update you have is official.
If it's a mod (language mod etc.), that's not how you're supposed to patch it.

**Comment by dzikk** [comment]
![polish](https://user-images.githubusercontent.com/22121054/231891576-df079e93-59ec-4a27-b847-ae88f0897c74.JPG)
![polish dlc](https://user-images.githubusercontent.com/22121054/231892056-bf8022c8-5d5b-468d-a9d5-b2cab863687d.JPG)
I totally dont know how I should consider this. Based on roms websites its official DLC.

**Comment by nozwock** [comment]
DLCs don't work. It's written on the front page of the project.

But since it's only a Language pack, it should be possible to extract its contents and pretty much just make a mod out of it and apply it.
