### ISSUE TITLE
Unicode issue...again

### ISSUE THREAD

**Issue by DarkAksoy** [nozwock/yanu#11]
how can i fix the error``
![Ekran Alıntısı](https://user-images.githubusercontent.com/105062378/228067392-c583a8c2-4545-4734-8c3c-ad2e99822ddf.JPG)

**Comment by nozwock** [comment]
Send logs, also try moving yanu to Desktop and launch it from there.

**Comment by nozwock** [comment]
I'll fix this in a later version, this unicode issue has resurfaced due to some changes in a previous version.

For now, just run yanu from a folder without any unicode characters.

**Comment by DarkAksoy** [comment]
i would run it on desktop and problem solved thank you very much for helping
