### ISSUE TITLE
Failed to build hac2l on 0.6.1 binary

### ISSUE THREAD

**Issue by EdyStauch** [nozwock/yanu#15]
I'm trying to run 0.6.1 pre-compiled binary on Ubuntu Linux x64 22.04 and i receive the error message "Failed to build hac2l".

I see on release notes of this version "Fixed hac2l not compiling on Linux due to a missing build flag.".

I'm not compiling i just want to run.

The message shows after select keys, base and update file.

**Comment by nozwock** [comment]
Yes likely, somebody else tried it on ubuntu as well, I think you'd need `g++` and maybe some other stuff.

**Comment by EdyStauch** [comment]
G++ was already installed. Do you have any other suggestions?

Running yanu on a terminal show more info. I hope it helps.

HEAD is now at 7fc1b3a hac2l: cap percentage calculation when progress-printing (closes #2)
Building linux_x64_release
make[1]: Entering directory '/tmp/.tmpHohebw/tools/hac2l'
fatal: ref HEAD is not a symbolic ref
fatal: ref HEAD is not a symbolic ref
fatal: ref HEAD is not a symbolic ref
result_get_name.cpp
Precompiling stratosphere.hpp for generic_linux_x64_release
ams_emummc_api.cpp
ams_exosphere_api.cpp
cal_battery_api.cpp
cal_crc_utils.cpp
cal_fs_utils.cpp
decodersrv_decoder_control_server_manager.cpp
decodersrv_decoder_control_service.cpp
decodersrv_decoder_server_object.cpp
decodersrv_software_jpeg_decoder.cpp
In file included from /tmp/.tmpHohebw/libraries/libstratosphere/source/capsrv/server/jpeg/decodersrv_software_jpeg_decoder.cpp:18:
/tmp/.tmpHohebw/libraries/libstratosphere/source/capsrv/server/jpeg/capsrv_server_jpeg_library_types.hpp:19:10: fatal error: **jpeglib.h: File or directory missing**
   19 | #include <jpeglib.h>
      |          ^~~~~~~~~~~
compilation terminated.
make[3]: *** [/tmp/.tmpHohebw/libraries/config//arch/x64/base_rules:13: decodersrv_software_jpeg_decoder.o] Erro 1
make[3]: ** Esperando que outros processos terminem.
make[2]: *** [/tmp/.tmpHohebw/libraries/config//../libstratosphere/libstratosphere.mk:111: all] Erro 2
make[1]: *** [/tmp/.tmpHohebw/tools/hac2l/tool.mk:89: check_lib] Erro 2

**Comment by nozwock** [comment]
> ```
> fatal error: jpeglib.h: File or directory missing
> 19 | #include <jpeglib.h>
> | ^~~~~~~~~~~
> compilation terminated.
> ```

You need this lib ofc, https://askubuntu.com/a/842884

**Comment by EdyStauch** [comment]
After installing the packages below it finally worked. 
If you find it useful, you could include these dependencies on the main page. 
Thank you very much.

sudo apt-get install libjpeg-turbo8-dev
sudo apt-get install binutils-dev

**Comment by nozwock** [comment]
Ya I'll include them
