### ISSUE TITLE
I want repack only base game and yanu still Request a update file

### ISSUE THREAD

**Issue by CrimsonSZ-Q** [nozwock/yanu#17]
So I want to try unpacking a rom (only rom without update), I use Termux. When I enter the command yanu unpack --base /storage/emulated/0/Switch/God Eater 3.nsp 
Yanu asked for the update file

**Comment by nozwock** [comment]
Oh that's true, I'll fix that

**Comment by nozwock** [comment]
Could you send what's the exact error?
Also send the log file.

**Comment by nozwock** [comment]
Because it works perfectly fine here.
I think you're just using an incorrect command.
![command](https://user-images.githubusercontent.com/57829219/230755799-dc4a842d-b636-4e90-823d-85cae9dd7b53.jpg)

![result](https://user-images.githubusercontent.com/57829219/230755808-1107960d-6869-49a8-8e31-39d0c76ff9ce.jpg)

**Comment by nozwock** [comment]
Ah wait, you're using `yanu`, that's just a short alias for updates only.
For accessing all the options you're supposed to use `yanu-cli` starting `0.7.0`.

**Comment by CrimsonSZ-Q** [comment]
> Ah wait, you're using `yanu`, that's just a short alias for updates only. For accessing all the options you're supposed to use `yanu-cli` starting `0.7.0`.

Ahh I see Thanks

**Comment by Genliz6** [comment]
> Ah wait, you're using `yanu`, on Termux, that's just a short alias for updates only. For accessing all the options you're supposed to use `yanu-cli` starting `0.7.0`.

![IMG_20230409_140850](https://user-images.githubusercontent.com/127250258/230759961-c56c5c0c-c933-4bff-a052-3f1302898a3d.jpg)

Hi, I'm a beginner. What command do I have to repack? i need a example

**Comment by nozwock** [comment]
Why are you copying the example one-to-one?

There's no such "123456.nca"
It even tell you

**Comment by nozwock** [comment]
You need to figure out which one is the control NCA in `patchdata` directory.
Look at the README, it mentions that the file is usually around ~1MiB.

**Comment by nozwock** [comment]
Maybe I should add a `--auto` to automatically get control NCA or something.

**Comment by Genliz6** [comment]
> Why are you copying the example one-to-one?
> 
> There's no such "123456.nca" It even tell you

![20230409_150621](https://user-images.githubusercontent.com/127250258/230761649-ba91008f-aa51-4a55-a0d8-a3e00994fd78.png)

i tried  But it's not work.  Do you have an example for me to see?

**Comment by Genliz6** [comment]
![IMG_20230409_153623](https://user-images.githubusercontent.com/127250258/230762876-a8d7fcf7-889d-4a4e-8e8d-615ba209baf0.jpg)

Ok! I can do it. thank you
