### ISSUE TITLE
unrecognized subcommand 'update-prompt'

### ISSUE THREAD

**Issue by bartche** [nozwock/yanu#27]
When using only 'yanu' in Termux.

> error: unrecognized subcommand 'update-prompt'
>     note: subcommand 'update' exists
>     note: to pass 'update-prompt' as a value, use 'yanu -- update-prompt'
> 
> Usage: yanu [OPTIONS] [COMMAND]

**Comment by nozwock** [comment]
It's fixed, reinstall yanu.
