### ISSUE TITLE
Path error in termux installer

### ISSUE THREAD

**Issue by goldug** [nozwock/yanu#28]
I'm following the guide and I get this error:
`Downloading 100% [=] (3.7/3.7 MB, 6.688 MB/s)
Extracted "yanu-cli-aarch64-termux_proot-linux-musl" to "/usr/bin/yanu"
/proc/self/fd/11: line 68: /data/data/com.termux/files/home/.local/bin:/data/data/com.termux/files/usr/bin/yanu-cli: No such file or directory 
Error: Failed to write entry script`

I think it's because $PATH shows multiple paths, one of which termux doesn't have permission to write to.
My fix is to just replace all occurances of $PATH with /data/data/com.termux/files/home/.local/bin

It's probably not an ideal solution, but it works.

**Comment by nozwock** [comment]
Why'd it not work?
Does `/data/data/com.termux/files/usr/bin` not exist for you?

**Comment by nozwock** [comment]
Ah is it because $PATH has multiple paths? Did you change it? it's not supposed to be like that iirc

**Comment by nozwock** [comment]
In that case replacing `$PATH` with `/data/data/com.termux/files/usr/bin` is a fine idea.

**Comment by nozwock** [comment]
Thanks

**Comment by goldug** [comment]
Yeah, I don't think I've edited the PATH before, but it's not impossible that something else did it for some reason. Maybe something termux changed?
In any case, just wanted to let you know that it at least *can* happen, and someone else might have the problem.
