### ISSUE TITLE
Error on termux update LOZ Tears of the kingdom 

### ISSUE THREAD

**Issue by FioriAlbania** [nozwock/yanu#29]
![Screenshot_2023-05-18-23-33-28-129_com termux](https://github.com/nozwock/yanu/assets/57939719/eea11118-20ae-4486-be4e-d4220560b3e3)

**Comment by FioriAlbania** [comment]
Other games work fine

**Comment by nozwock** [comment]
I think totk only works with the pc version for now.

**Comment by nozwock** [comment]
I may consider addressing this issue for Termux at some point in the future.
