### ISSUE TITLE
I was trying to update pokemon shield rom but this error showing in termux

### ISSUE THREAD

**Issue by sasimanto** [nozwock/yanu#3]
Extracting romfs/exefs...
Extracted romfs/exefs (33 seconds)              Cleaned up extracted NSPs data (34 seconds)
Error: Failed to pack romfs/exefs to NCA        
Location:
    /project/src/hac/patch.rs:300:9

**Comment by nozwock** [comment]
@sasimanto you should've send the logs while filling an issue.
Also take a look at the Notes section in [#About](https://github.com/nozwock/yanu#about).

At the moment, Android build supports less number of games than the PC builds.

**Comment by sasimanto** [comment]
Thanks!
