### ISSUE TITLE
Failed to find base NCA?

### ISSUE THREAD

**Issue by Rik-Kirtaniya** [nozwock/yanu#30]
I was trying to update a game NSP with an update NSP on windows, with the 16.0.2 prod.keys and title.keys file, but I keep running into this error where it says "Failed to find base NCA" in the first NSP file. I am quite new to this and I might be doing something wrong, so I would appreciate some help.

**Comment by nozwock** [comment]
Send logs (by drag and dropping the file in the text box), I'll take a look tomorrow morning.

**Comment by Rik-Kirtaniya** [comment]
Sure, here's both the screenshot of the error, as well as the log that was generated.
![image](https://github.com/nozwock/yanu/assets/68043903/10790442-549d-41e9-be69-5626a0fe201d)
[yanu.log.2023-05-23-18.txt](https://github.com/nozwock/yanu/files/11547348/yanu.log.2023-05-23-18.txt)

**Comment by nozwock** [comment]
This was only first half of the log, there should be another file. Also try using newer keys.

**Comment by Rik-Kirtaniya** [comment]
Isn't 16.0.2 the latest one? I tried it again after redownloading them, but this is all that appears in the command prompt.
![image](https://github.com/nozwock/yanu/assets/68043903/052edd9a-d309-464a-833b-8d5ece01e1d0)
The process pretty much aborts itself after that. And unfortunately, this is the only logfile that is generated, I tried the process over again and the new logfile is identical. I made sure to import both the necessary keyfiles as well
[yanu.log.2023-05-23-18.txt](https://github.com/nozwock/yanu/files/11547463/yanu.log.2023-05-23-18.txt)

I am not sure if it has something to do with the game NSPs themselves being old (?) though I can't rationalize if that would matter in any way.

**Comment by nozwock** [comment]
Hmm? I think 16.0.3 is the latest.

**Comment by Rik-Kirtaniya** [comment]
Update, so I installed Termux on Android and then installed yanu on my phone with the bash command, and then used the _exact same_ NSPs and the _exact same_ keys, and it worked perfectly. It patched it without a single error and I could then emulate it in Skyline perfectly, with it showing the updated version number.

Seems like this issue I faced occurred only when using the windows executable for some reason. Are there perhaps any dependencies or such that might be missing on a layman user's windows environment?

**Comment by nozwock** [comment]
If that's the case then try updating on windows with the Hactool and Hac2l extractors in Config.

**Comment by Rik-Kirtaniya** [comment]
Just tried changing the NSP Extractor to Hactool and NCA Extractor to Hac2l in the windows executable's GUI, but it sadly gives the same error as with the other options.

**Comment by nozwock** [comment]
Send the logs for that configuration. I'd take a look.

**Comment by Rik-Kirtaniya** [comment]
[yanu.log.2023-05-24-04.txt](https://github.com/nozwock/yanu/files/11550381/yanu.log.2023-05-24-04.txt)
There we go. And yes, this was the only logfile that was generated.

**Comment by nozwock** [comment]
> [yanu.log.2023-05-24-04.txt](https://github.com/nozwock/yanu/files/11550381/yanu.log.2023-05-24-04.txt) There we go. And yes, this was the only logfile that was generated.

Sorry for the delayed response. I had previously instructed you to use Hactool and Hac2l extractors in Config. However, I looked over the logs and it's still using the Hactoolnet, hence the errors.

**Comment by Rik-Kirtaniya** [comment]
I see, so I guess selecting the right options in the GUI's Config menu is somehow not reflecting to actually changing the settings?

**Comment by nozwock** [comment]
That weirdly seems to be the case, I'll take a look.

**Comment by nozwock** [comment]
Actually no, that's just for reading the files. It tries to read first with Hactoolnet and uses Hac2l as a fallback.

**Comment by nozwock** [comment]
If you could provide me with the logs from both Termux and PC, I can investigate this issue further. However, you can consider the issue resolved if you prefer.
