### ISSUE TITLE
Yanu doesn't work with sd card 

### ISSUE THREAD

**Issue by BRUHGMAISNJDFIAs** [nozwock/yanu#33]
![Screenshot_2023-06-15-16-12-39-518-edit_com termux](https://github.com/nozwock/yanu/assets/111080781/adfb4563-d536-4206-be32-92384c16dafb)

**Comment by nozwock** [comment]
Because the application isn't aware of it. You'd have to add `--bind /storage/5C30-DC28/` to the below entry script.
![Screenshot_2023-06-15-22-44-15-52_84d3000e3f4017145260f7618db1d683.jpg](https://github.com/nozwock/yanu/assets/57829219/4e40c201-fd05-4d5c-9aa5-b4c94dd554bd)

**Comment by nozwock** [comment]
A simple `--bind /storage` would probably work, but I don't know what other implications it might have.

**Comment by BRUHGMAISNJDFIAs** [comment]
worked thank you
