### ISSUE TITLE
How to delete temp directory?

### ISSUE THREAD

**Issue by StevenBeach33** [nozwock/yanu#34]
While updating an NSP, with result of fail (failed to pack FS files to NCA) 
Location :
/project/crates/hac/src/vfs/nca.rs

And my storage still used with that patching

**Comment by nozwock** [comment]
In case they're not cleaned, that must be in the Home directory as such:
![Screenshot_2023-06-18-17-34-36-88_84d3000e3f4017145260f7618db1d683.jpg](https://github.com/nozwock/yanu/assets/57829219/e2183cba-76b5-4260-82b9-379dc9795ae1)

You can view the contents of Home with `ls -a`, and delete the files with `rm -rf ~/.tmp*`.
