### ISSUE TITLE
`yanu-cli` commands not working

### ISSUE THREAD

**Issue by EnderNon** [nozwock/yanu#39]
my yanu directory is set to /sdcard/yanu and inside i have prod.keys and title.keys (both set up), and a nsp file that I'd like to unpack. when i run 
```shell
yanu-cli unpack --base /sdcard/yanu/thegame.nsp
```
i get an error about missing base parameter.

when i run
```shell
yanu-cli unpack --base thegame.nsp
```
i am prompted to select a file. upon selecting the game, it tells me there's no other 2nd file to select. If it matters, I am using android 13, termux latest debug version

**Comment by nozwock** [comment]
> i get an error about missing base parameter.

It should work, you'd need to send me the output to look into this further.

**Comment by nozwock** [comment]
I'm sorry, turns out it was a bug caused by a recent update for the termux script.
