### ISSUE TITLE
Failed to find Base NCA due to missing `libbfd-2.38-system.so`, required by dated `hac2l` build

### ISSUE THREAD

**Issue by fedeharuchan** [nozwock/yanu#44]
a few days i formated my sd, so i had to get my games again. I download them from the same source, but now i cant update them. when i try i get this error. last time i tried a few months ago didnt have this problem
![Screenshot_2023-10-26-16-59-10-182_com termux-edit](https://github.com/nozwock/yanu/assets/14883721/04ffdc33-e1e6-486d-89a6-87e052e1cf6b)

**Comment by mengchangji** [comment]
So do I/So am I/Me too.

**Comment by mengchangji** [comment]
Have you solved it?

**Comment by dan3840** [comment]
I have the same problem

**Comment by fedeharuchan** [comment]
No, seems like the script Is broken. Saw a few Reddit post that have the dame problem

**Comment by dan3840** [comment]
I looked at this error in the log, maybe this is the problem:
com.github.nozwock.yanu/hac2l: error while loading shared libraries: libbfd-2.38-system.so: cannot open shared object file: No such file or directory

**Comment by mengchangji** [comment]
have already been solved

**Comment by dan3840** [comment]
> have already been solved

How did you solve it?

**Comment by mengchangji** [comment]
It needs to be used in conjunction with the code 'root distro login ubuntu -- bash - c' cp/sdcard/Download/libbfd-2.38-system. so/usr/lib/arch64 Linux gnu/'and libbfd-2.38-system. so files

**Comment by dan3840** [comment]
> It needs to be used in conjunction with the code 'root distro login ubuntu -- bash - c' cp/sdcard/Download/libbfd-2.38-system. so/usr/lib/arch64 Linux gnu/'and libbfd-2.38-system. so files

Would you have any means of contact like Telegram, I couldn't understand very well. Do you have a video on how to do it or a tutorial or something?

**Comment by dan3840** [comment]
Where did you find this downloadable lib?

**Comment by dan3840** [comment]
> No, seems like the script Is broken. Saw a few Reddit post that have the same problem

I made a temporary script to fix the problem: https://github.com/dan3840/yanu

If you want to test it, clear the app Termux data and download using my script.

**Comment by fedeharuchan** [comment]
> > have already been solved
> 
> How did you solve it?

your forks works fine, thanks

**Comment by dan3840** [comment]
> > > have already been solved
> > 
> > 
> > How did you solve it?
> 
> your forks works fine, thanks

Okay friend, I deleted the message to make a correction. 

If you need it, here is the updated repository:
https://github.com/dan3840/yanu

**Comment by nozwock** [comment]
This issue with missing libraries is probably because the hac2l in use was compiled with older versions of libraries, which are now absent since they were replaced with the latest versions during a system update.

**Comment by nozwock** [comment]
A workaround would be to symlink to the newer library. The following command does that:
```bash
proot-distro login ubuntu -- sh -c 'ln -s "$(find /usr/lib/aarch64-linux-gnu/ -type f -name '"'libbfd*'"' | head -n1)" '"'/usr/lib/aarch64-linux-gnu/libbfd-2.38-system.so'"
```

**Comment by nozwock** [comment]
For now, I've added a workaround in the [installation script](https://github.com/nozwock/yanu#android-wtermux). So, those experiencing the issue can simply re-install.

**Comment by TomatoJuicee** [comment]
> For now, I've added a workaround in the [installation script](https://github.com/nozwock/yanu#android-wtermux). So, those experiencing the issue can simply re-install.

I still facing this problem, i re-installed yanu twitce already can you help me?

**Comment by TomatoJuicee** [comment]
> For now, I've added a workaround in the [installation script](https://github.com/nozwock/yanu#android-wtermux). So, those experiencing the issue can simply re-install.

![Yanu.jpg](https://github.com/user-attachments/assets/16ceb51b-17f4-45f7-a042-947cade5aa0a)

Here

**Comment by VeckerYT** [comment]
> > > > have already been solved
> > > 
> > > 
> > > How did you solve it?
> > 
> > 
> > your forks works fine, thanks
> 
> Okay friend, I deleted the message to make a correction.
> 
> If you need it, here is the updated repository: https://github.com/dan3840/yanu

error 404 wedpage removed

can you please reupload it 
![Uploading image_2024-12-08_001648645.png…]()

**Comment by nozwock** [comment]
> > If you need it, here is the updated repository: https://github.com/dan3840/yanu
> 
> error 404 wedpage removed
> 
> can you please reupload it 
> ![Uploading image_2024-12-08_001648645.png…]()
> 

You shouldn't be having this exact issue? I had added a workaround for it during the installation process quite a while ago.

**Comment by VeckerYT** [comment]
Can You Help Me With That ? @nozwock

**Comment by nozwock** [comment]
> Can You Help Me With That ? @nozwock 

With what? You've not provided me with any information about the issue you're facing.

**Comment by VeckerC** [comment]
I Am Having The Same Issue, Unfortunately The Page is removed for the file you used, so do you have the file or any other way to fix the same issue that now i am facing

**Comment by VeckerC** [comment]
> > Can You Help Me With That ? @nozwock
> 
> With what? You've not provided me with any information about the issue you're facing.

I Am Having The Same Issue, Unfortunately The Page is removed for the file you used, so do you have the file or any other way to fix the same issue that now i am facing

**Comment by nozwock** [comment]
@VeckerC I mentioned this above.

> You shouldn't be having this exact issue? I had added a workaround for it in the installation process quite a while ago.

Try reinstalling and see if that fixes your issue.
