### ISSUE TITLE
Can't locate SD card on Android

### ISSUE THREAD

**Issue by jarz54** [nozwock/yanu#48]
now yuzu is dead, skyline is my back up emulator,i tried to patch a file located on sd card,but it can't locate the path if its on sd card, what should I do,im using android btw

**Comment by nozwock** [comment]
Could you send me the logs? I can't help much otherwise.

My device doesn't have a sdcard slot, so I can't try to reproduce the issue myself.

**Comment by nozwock** [comment]
@jarz54 I've added support for external storage, you may now try again.

Rerun the [installation script](https://github.com/nozwock/yanu?tab=readme-ov-file#android-wtermux) to get the update.

Now, I've only tested this on a single device, so in case the SD card still isn't detected, run the following command with the path to your external storage (SD card, etc):
```
echo '/storage/148F-1F00' >> "$HOME/.config/com.github.nozwock.yanu/proot-bindings"
```
Replace `/storage/148F-1F00` with your own SD card's path.
