### ISSUE TITLE
Cant patch because full of storage

### ISSUE THREAD

**Issue by vannessqn** [nozwock/yanu#6]
My "media storage" system is taking 44GB trying to patch diablo 3 and yanu said storage full cant patch, can you show me how to delete the "temp" patch files so I can clear more storage before patch the rom thank you!

**Comment by nozwock** [comment]
Hmm, that's bizarre. Shouldn't take more than 2-3x storage.

Anyways my bad on putting tempfiles in an inconvenient place in the current version. I'll improve this later; busy with exams.

Here's how to delete the tempfiles as of the latest version:
```sh
proot-distro login ubuntu
```
Then,
```sh
rm -rf /usr/bin/.tmp*
```

**Comment by vannessqn** [comment]
Nothing happened https://ibb.co/5B7s2D1 https://ibb.co/rc1m6jK
https://ibb.co/fHjH94J

**Comment by nozwock** [comment]
> Nothing happened https://ibb.co/5B7s2D1 https://ibb.co/rc1m6jK
> https://ibb.co/fHjH94J

How much storage is Termux even taking?

It'd have no effect if there are no tempfiles obviously.

Ofc if that's not the case and termux is taking lots of storage then you can try reinstalling termux.

**Comment by nozwock** [comment]
@vannessqn I just looked at your ss, Media storage has nothing to do with yanu. 🫤

**Comment by vannessqn** [comment]
Im googling and its seem for some on android 11 (me) Media storage just count all the media files in it, I havent look at my storage for a while so I didnt know how many GB I have before and after download diablo 3/update/termux and running it

**Comment by vannessqn** [comment]
Yup I just cleared some storages and patch the game now the updated diablo not even launching lmao anyway thank for the help appreciate it!
